config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations', passwords: 'passwords' }

  resources :articles do
    resources :comments, only: [:create, :destroy]
  end

  resource :user, only: [:show]

  resource :admin, only: [:show] do
    resource :user, only: [:update, :index]
  end

  get 'admin/users' => 'admins#change_users'
  get 'admin/articles' => 'admins#change_articles'

  resources :search, only: [:index]
  get 'search/user' => 'search#find_user'
  get 'search/article' => 'search#find_article'

  root 'articles#index'

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  skip_before_filter :authenticate_user!, only: [:index]
  before_action :check_permission, except: [:index]

  def index
    return @articles = [] unless valid_query?(params[:query])

    @articles = find_in Article
    @pagination = @articles
  end

  def find_article
    index

    create_response(@articles, 'admins/_articles')
  end

  def find_user
    if valid_query?(params[:query])
      @users = find_in User
    else
      @users = []
    end

    create_response(@users, 'admins/_users')
  end

  private

  def find_in object
    object.search(params[:query])
        .page(params[:page])
        .per(10)
  end

  def valid_query? query
    query && query.size > 0
  end

  def create_response data, partial
    if data.size > 0
      render partial, layout: false
    else
      render status: 422, text: t('search.error')
    end
  end

end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/index.html.haml
%h2= t('search.result')

= form_tag search_index_path, method: :get, class: ['search-form']  do
  #imaginary_container.container-fluid
    .input-group.stylish-input-group
      = text_field_tag :query, params[:query], class: 'form-control', placeholder: t('search.placehodler')
      %span.input-group-addon
        %button{ type: 'submit' }
          %span.glyphicon.glyphicon-search

.articles-index
  - @articles.each do |article|
    %div.preview-article
      = render article
      %br
      = link_to t('articles.readArticle'), article_path(article), class: ['btn', 'btn-default', 'read-article']
      - if is_admin?
        = link_to t('articles.removeArticle'), article_path(article), class: ['btn', 'btn-danger', 'remove-article', 'pull-right']