config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations', passwords: 'passwords' }

  resources :articles do
    resources :comments, only: [:create, :destroy]
  end

  resource :user, only: [:show]

  resource :admin, only: [:show] do
    resource :user, only: [:update, :index]
  end

  get 'admin/users' => 'admins#change_users'
  get 'admin/articles' => 'admins#change_articles'

  resources :search, only: [:index]
  get 'search/user' => 'search#find_user'
  get 'search/article' => 'search#find_article'

  root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base

  include PgSearch

  has_many :comments, dependent: :destroy
  has_many :taggings
  has_many :tags, through: :taggings
  belongs_to :user

  validates :title, length: { minimum: 2 }
  validates :content, length: { minimum: 2 }

  pg_search_scope :search,
                  against: [:title, :content],
                  associated_against: {
                      tags: [:name]
                  },
                  :using => {
                      :tsearch => {:prefix => true}
                  }

  def article_tags
    self.tags.collect(&:name).join(', ')
  end

  def article_tags=(tags_list)
    tags_arr = check_tags(tags_list)

    tags = Tag.where(name: tags_arr) || []

    self.tags = tags
  end

  private

  def check_tags tags_list
    return [] unless tags_list.present?
    tags = tags_list.split(/\s*,\s*/)

    tags.each do |el|
      unless Tag.find_by_name(el)
        Tag.create(name: el)
      end
    end

    tags
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  skip_before_filter :authenticate_user!, only: [:index, :show]
  before_action :check_permission, except: [:index, :show]

  def index
    @articles = Article.order(:created_at)
                       .reverse_order
                       .page(params[:page])
                       .per(10)

    @pagination = @articles
  end

  def show
    @article = Article.find(params[:id])
    @comments = @article.comments.reverse_order
    @comment = Comment.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      render plain: article_path(@article)
    else
      render status: 422, json: @article.errors.full_messages
    end
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params.merge(user_id: get_user_id))

    if @article.save
      render plain: article_path(@article)
    else
      render status: 422, json: @article.errors.full_messages
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :content, :label, :article_tags)
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper

  def get_article_button_text article
    if article.new_record?
      t('articles.createArticle')
    else
      t('articles.updateArticle')
    end
  end

end

app/views/articles/_article.html.haml
%header
  %h2
    = link_to article.title, article

  - article.tags.each do |tag|
    = link_to tag.name, search_index_path(query: tag.name), class: ['label', 'label-primary']

%article.article= article.content.html_safe

app/views/articles/_form.html.haml
= form_for @article, remote: true, html: { class: 'article-form' } do |f|

  %p
    %h4= t('articles.title')
    = f.text_field :title, class: ['form-control', 'article-title'], placeholder: t('articles.titlePlaceHolder')

  %p
    %h4= t('articles.tags')
    = f.text_field :article_tags, class: ['form-control', 'article-tags'], placeholder: t('articles.tagsPlaceholder')


  %p
    %h4= t('articles.content')
    = f.text_area :content, class: ['summernote', 'article-content']

  %p
    = f.submit get_article_button_text(@article), class: ['btn', 'btn-success', 'pull-right']
    - if edit
      = link_to t('articles.removeArticle'), articles_path, class: ['btn', 'btn-danger'], method: :destroy


.alert.alert-danger.article-error
  %strong= t('error')
  .article-error-content

app/views/articles/edit.html.haml
%h1= t('articles.editArticle')

= render 'form', edit: true

app/views/articles/index.html.haml
- if is_admin?
  = link_to t('articles.createArticle'), new_article_path, class: ['btn', 'btn-success']

.articles-index
  - @articles.each do |article|
    %div.preview-article
      = render article
      %br
      = link_to t('articles.readArticle'), article_path(article), class: ['btn', 'btn-default', 'read-article']
      - if is_admin?
        = link_to t('articles.removeArticle'), article_path(article), method: :delete, class: ['btn', 'btn-danger', 'remove-article', 'pull-right']

app/views/articles/new.html.haml
%h1= t('articles.createArticle')

= render 'form', edit: false

app/views/articles/show.html.haml
- if is_admin?
  = link_to t('layout.edit'), edit_article_path(@article)

= render 'article', article: @article

%nav.bottom-navigation
  = link_to t('layout.navigation.main'), articles_path
  - if is_admin?
    | #{link_to t('layout.edit'), edit_article_path(@article)}

%h4= t('articles.comments.comments')

= form_for([@article, @article.comments.build], html: { class: 'add-comment' }) do |f|
  = f.text_area :body, class: ['comment-body', 'form-control'], placeholder: t('articles.comments.inputComment'), row: 3
  %br
  = f.submit t('articles.comments.addComment'), class: ['btn', 'btn-default']

.comment-error.alert.alert-danger
  %strong= t('error')
  .comment-error-content
    
.comments= render @comments