config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations', passwords: 'passwords' }

  resources :articles do
    resources :comments, only: [:create, :destroy]
  end

  resource :user, only: [:show]

  resource :admin, only: [:show] do
    resource :user, only: [:update, :index]
  end

  get 'admin/users' => 'admins#change_users'
  get 'admin/articles' => 'admins#change_articles'

  resources :search, only: [:index]
  get 'search/user' => 'search#find_user'
  get 'search/article' => 'search#find_article'

  root 'articles#index'

end

app/views/layouts/_header.html.haml
%header.navbar-inverse{:role => 'navigation'}
  .container-fluid
    .navbar-header
      = link_to 'Webinfo', root_path, class: 'navbar-brand'

    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right.user-info
        %li
          = form_tag search_index_path, method: :get, class: ['navbar-form', 'navbar-left'], role: 'search' do
            .form-group
              = text_field_tag :query, params[:query], class: 'form-control', placeholder: t('search.placehodler')
            = submit_tag t('search.button'), class: ['btn', 'btn-default']

        - if current_user
          = render 'layouts/logout'
        - else
          = render 'layouts/login'

app/views/layouts/_login.html.haml
%li
  = link_to t('authentication.login'), new_user_session_path
  -#= form_for :user, url: new_user_session_path, html: { method: :post, role: 'login', class: ['navbar-form', 'navbar-left', 'navbar-login']} do |f|
  -#  .form-group
  -#    = f.email_field :email, class: 'form-control', placeholder: 'Email'
  -#    = f.password_field :password, autocomplete: 'off', class: 'form-control', placeholder: 'Password'
  -#    = f.submit 'Login', class: ['btn', 'btn-invert', 'navbar-btn']

app/views/layouts/_logout.html.haml
- if is_admin?
  %li
    %p.navbar-text
      =link_to t('admins.administration'), admin_path

%li
  %p.navbar-text
    = "#{t('authentication.hello')}, #{link_to current_user.name, user_path}!".html_safe

%li
  = link_to t('authentication.exit'), destroy_user_session_path, method: :delete

app/views/layouts/_navigation.html.haml
%nav.navigation
  %ul.nav
    %li
      = link_to t('layout.navigation.main'), root_path
    %li
      = link_to t('search.button'), search_index_path

    - if current_user
      %li
        = link_to t('layout.navigation.profile'), user_path

    - else
      %li
        = link_to t('authentication.login'), new_user_session_path
      %li
        = link_to t('authentication.registration'), new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type'}/
    %title Blog
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false
    = javascript_include_tag 'application', 'data-turbolinks-track' => false
    = csrf_meta_tags
  %body
    = render 'layouts/header'

    %main.container.application-content
      .col-md-10.col-xs-15
        = yield

      .col-md-2.col-xs-3
        = render 'layouts/navigation'

    - if @pagination
      %section.container
        = paginate @pagination